stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python -m src.data.data_preprocessing
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim
